import type { SelectOption } from '@/components/ui/Select';

export const SPAIN_PROVINCES: ReadonlyArray<SelectOption> = [
  { value: 'Álava', label: 'Álava' },
  { value: 'Albacete', label: 'Albacete' },
  { value: 'Alicante', label: 'Alicante' },
  { value: 'Almería', label: 'Almería' },
  { value: 'Ávila', label: 'Ávila' },
  { value: 'Badajoz', label: 'Badajoz' },
  { value: 'Barcelona', label: 'Barcelona' },
  { value: 'Burgos', label: 'Burgos' },
  { value: 'Cáceres', label: 'Cáceres' },
  { value: 'Cádiz', label: 'Cádiz' },
  { value: 'Cantabria', label: 'Cantabria' },
  { value: 'Castellón', label: 'Castellón' },
  { value: 'Ciudad Real', label: 'Ciudad Real' },
  { value: 'Córdoba', label: 'Córdoba' },
  { value: 'Cuenca', label: 'Cuenca' },
  { value: 'Gerona', label: 'Gerona' },
  { value: 'Granada', label: 'Granada' },
  { value: 'Guadalajara', label: 'Guadalajara' },
  { value: 'Guipúzcoa', label: 'Guipúzcoa' },
  { value: 'Huelva', label: 'Huelva' },
  { value: 'Huesca', label: 'Huesca' },
  { value: 'Jaén', label: 'Jaén' },
  { value: 'León', label: 'León' },
  { value: 'Lérida', label: 'Lérida' },
  { value: 'La Rioja', label: 'La Rioja' },
  { value: 'Lugo', label: 'Lugo' },
  { value: 'Madrid', label: 'Madrid' },
  { value: 'Málaga', label: 'Málaga' },
  { value: 'Murcia', label: 'Murcia' },
  { value: 'Nafra', label: 'Nafra' },
  { value: 'Navarra', label: 'Navarra' },
  { value: 'Orense', label: 'Orense' },
  { value: 'Ourense', label: 'Ourense' },
  { value: 'Palencia', label: 'Palencia' },
  { value: 'Pontevedra', label: 'Pontevedra' },
  { value: 'Sevilla', label: 'Sevilla' },
  { value: 'Segovia', label: 'Segovia' },
  { value: 'Soria', label: 'Soria' },
  { value: 'Tarragona', label: 'Tarragona' },
  { value: 'Teruel', label: 'Teruel' },
  { value: 'Toledo', label: 'Toledo' },
  { value: 'Valencia', label: 'Valencia' },
  { value: 'Valladolid', label: 'Valladolid' },
  { value: 'Bizkaia', label: 'Bizkaia' },
  { value: 'Zamora', label: 'Zamora' },
  { value: 'Zaragoza', label: 'Zaragoza' },
  { value: 'Ceuta', label: 'Ceuta' },
  { value: 'Melilla', label: 'Melilla' },
];
