export const ROUTES = {
  HOME: '/',
  CATALOG: '/catalog',
  LOGIN: '/login',
  REGISTER: '/register',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  PRODUCT_DETAIL: (id: string) => `/products/${id}`,
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  ORDER_CONFIRMATION: (id: string) => `/orders/${id}/confirmation`,
  ADMIN: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_NEW: '/admin/products/new',
  ADMIN_PRODUCT_EDIT: (id: string) => `/admin/products/${id}/edit`,
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_UPLOADS: '/admin/uploads',
  ADMIN_USERS: '/admin/users',
  ADMIN_USER_NEW: '/admin/users/new',
  ADMIN_USER_EDIT: (id: string) => `/admin/users/${id}/edit`,
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_CATEGORY_NEW: '/admin/categories/new',
  ADMIN_CATEGORY_EDIT: (id: string) => `/admin/categories/${id}/edit`,
  ADMIN_ANALYTICS: '/admin/analytics',
  ADMIN_AUDIT: '/admin/audit',
  ADMIN_SETTINGS: '/admin/settings',
  NOT_FOUND: '/404',
  UNAUTHORIZED: '/403',
} as const;
