export const ROUTES = {
  HOME: '/',
  CATALOG: '/catalog',
  LOGIN: '/login',
  REGISTER: '/register',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  PRODUCT_DETAIL: (id: string) => `/products/${id}`,
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  ADMIN: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_NEW: '/admin/products/new',
  ADMIN_PRODUCT_EDIT: (id: string) => `/admin/products/${id}/edit`,
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_UPLOADS: '/admin/uploads',
  NOT_FOUND: '/404',
  UNAUTHORIZED: '/403',
} as const;
